-- P118 / 01: 專案資料表
-- 前置條件：Supabase 已啟用 PostGIS，且擴充套件位於 extensions schema。

create table if not exists public."TblP118HistoricalEntity" (
  "EntityID" bigint generated by default as identity primary key,
  "Slug" text not null unique,
  "TitleZh" text not null,
  "TitleEn" text,
  "StartYear" integer not null,
  "EndYear" integer not null,
  "SummaryZh" text not null,
  "SummaryEn" text,
  "SourceCitation" text,
  "SourceURL" text,
  "DisplayColor" text not null default '#D06A42',
  "IsPublished" boolean not null default false,
  "CreatedAt" timestamptz not null default now(),
  "UpdatedAt" timestamptz not null default now(),
  constraint "CkP118EntityYearOrder" check ("StartYear" <= "EndYear"),
  constraint "CkP118EntityNoYearZero" check ("StartYear" <> 0 and "EndYear" <> 0),
  constraint "CkP118EntityColor" check ("DisplayColor" ~ '^#[0-9A-Fa-f]{6}$')
);

create table if not exists public."TblP118HistoricalGeometry" (
  "GeometryID" bigint generated by default as identity primary key,
  "EntityID" bigint not null references public."TblP118HistoricalEntity" ("EntityID") on delete cascade,
  "Geometry" extensions.geometry(MultiPolygon, 4326) not null,
  "LabelPoint" extensions.geometry(Point, 4326),
  "GeometryNote" text,
  "SortOrder" integer not null default 0,
  "CreatedAt" timestamptz not null default now(),
  "UpdatedAt" timestamptz not null default now()
);
