-- P118 / 01: 專案資料表（V0.2 遺址點位版）
-- 本版以一般數值欄位保存經緯度，不需要 PostGIS。
-- 若資料庫已有 V0.1 的 TblP118HistoricalGeometry，本檔不會刪除或修改它。

create table if not exists public."TblP118HistoricalEntity" (
  "EntityID" bigint generated by default as identity primary key,
  "Slug" text not null unique,
  "TitleZh" text not null,
  "TitleEn" text,
  "StartYear" integer not null,
  "EndYear" integer not null,
  "SummaryZh" text not null,
  "SummaryEn" text,
  "SourceCitation" text,
  "SourceURL" text,
  "DisplayColor" text not null default '#D06A42',
  "IsPublished" boolean not null default false,
  "CreatedAt" timestamptz not null default now(),
  "UpdatedAt" timestamptz not null default now(),
  constraint "CkP118EntityYearOrder" check ("StartYear" <= "EndYear"),
  constraint "CkP118EntityNoYearZero" check ("StartYear" <> 0 and "EndYear" <> 0),
  constraint "CkP118EntityColor" check ("DisplayColor" ~ '^#[0-9A-Fa-f]{6}$')
);

create table if not exists public."TblP118ArchaeologicalSite" (
  "SiteID" bigint generated by default as identity primary key,
  "Slug" text not null unique,
  "SiteNameZh" text not null,
  "SiteNameEn" text,
  "Longitude" double precision not null,
  "Latitude" double precision not null,
  "LocationNote" text,
  "SourceCitation" text,
  "SourceURL" text,
  "IsPublished" boolean not null default false,
  "CreatedAt" timestamptz not null default now(),
  "UpdatedAt" timestamptz not null default now(),
  constraint "CkP118SiteLongitude" check ("Longitude" between -180 and 180),
  constraint "CkP118SiteLatitude" check ("Latitude" between -90 and 90)
);

create table if not exists public."TblP118EntitySite" (
  "EntitySiteID" bigint generated by default as identity primary key,
  "EntityID" bigint not null references public."TblP118HistoricalEntity" ("EntityID") on delete cascade,
  "SiteID" bigint not null references public."TblP118ArchaeologicalSite" ("SiteID") on delete cascade,
  "EvidenceNote" text,
  "IsPrimary" boolean not null default false,
  "SortOrder" integer not null default 0,
  "CreatedAt" timestamptz not null default now(),
  "UpdatedAt" timestamptz not null default now(),
  constraint "UqP118EntitySite" unique ("EntityID", "SiteID")
);
