-- P118 / 11: 全球同期事件（V0.4）
-- 安全範圍：只建立或修改 TblP118ContextEvent、其P118索引／Policy與P118_GetContextEvents()。
-- 不接觸其他專案資料表、函式、RLS、Policy或public schema全域權限。本檔可重複執行。

begin;

create table if not exists public."TblP118ContextEvent" (
  "EventID" bigint generated by default as identity primary key,
  "Slug" text not null unique,
  "TitleZh" text not null,
  "TitleEn" text,
  "StartYear" integer not null,
  "EndYear" integer not null,
  "TriggerYear" integer not null,
  "Category" text not null,
  "RegionName" text,
  "SummaryZh" text,
  "SourceCitation" text,
  "SourceURL" text,
  "DisplayPriority" integer not null default 50,
  "IsPublished" boolean not null default false,
  "CreatedAt" timestamptz not null default now(),
  "UpdatedAt" timestamptz not null default now(),
  constraint "CkP118ContextYearOrder" check ("StartYear" <= "EndYear"),
  constraint "CkP118ContextNoYearZero" check (
    "StartYear" <> 0 and "EndYear" <> 0 and "TriggerYear" <> 0
  ),
  constraint "CkP118ContextTriggerRange" check (
    "TriggerYear" between "StartYear" and "EndYear"
  ),
  constraint "CkP118ContextPriority" check ("DisplayPriority" between 0 and 100)
);

create index if not exists "IxP118ContextPublishedYear"
  on public."TblP118ContextEvent" ("IsPublished", "TriggerYear", "DisplayPriority" desc);

alter table public."TblP118ContextEvent" enable row level security;

do $P118$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'TblP118ContextEvent'
      and policyname = 'P118_PublicReadPublishedContext'
  ) then
    create policy "P118_PublicReadPublishedContext"
      on public."TblP118ContextEvent"
      for select
      to anon, authenticated
      using ("IsPublished" = true);
  end if;
end
$P118$;

insert into public."TblP118ContextEvent" (
  "Slug", "TitleZh", "TitleEn", "StartYear", "EndYear", "TriggerYear",
  "Category", "RegionName", "SummaryZh", "SourceCitation", "SourceURL",
  "DisplayPriority", "IsPublished"
)
values
  ('gobekli-tepe', '哥貝克力石陣開始建造', 'Construction begins at Gobekli Tepe',
    -9600, -8200, -9600, '考古遺址', '安納托利亞',
    '今土耳其東南部的大型史前建築群，年代早於成熟農業社會。年代為約數。',
    'UNESCO World Heritage Centre, Göbekli Tepe.', 'https://whc.unesco.org/en/list/1572/', 90, true),
  ('uruk-writing', '美索不達米亞早期文字出現', 'Early writing appears in Mesopotamia',
    -3400, -3200, -3400, '文字', '美索不達米亞',
    '烏魯克時期的行政記錄逐步發展為早期楔形文字；年代為約數。',
    'The British Museum, Mesopotamia collections and learning resources.',
    'https://www.britishmuseum.org/collection/galleries/mesopotamia-6000-1500-bc', 90, true),
  ('stonehenge', '巨石陣主要建造階段', 'Main construction phases of Stonehenge',
    -3000, -2500, -3000, '建築', '不列顛',
    '英格蘭南部巨石陣的重要建造階段，反映新石器時代的儀式地景。年代為約數。',
    'UNESCO World Heritage Centre, Stonehenge, Avebury and Associated Sites.',
    'https://whc.unesco.org/en/list/373/', 75, true),
  ('great-pyramid', '吉薩大金字塔興建', 'Great Pyramid of Giza constructed',
    -2580, -2560, -2580, '建築', '埃及',
    '胡夫金字塔約於古王國第四王朝興建；不同年表對精確年代略有差異。',
    'The Metropolitan Museum of Art, Egypt in the Old Kingdom.',
    'https://www.metmuseum.org/toah/ht/03/afe.html', 100, true),
  ('hammurabi', '漢摩拉比統治巴比倫', 'Reign of Hammurabi of Babylon',
    -1792, -1750, -1792, '政治與法律', '巴比倫',
    '漢摩拉比在位期間完成統一與法制建設；著名法典石碑約屬其統治晚期。',
    'The Metropolitan Museum of Art, Mesopotamia chronology; Musée du Louvre, Code of Hammurabi.',
    'https://collections.louvre.fr/en/ark:/53355/cl010174436', 90, true),
  ('oracle-bones', '商代甲骨文記錄', 'Shang oracle-bone inscriptions',
    -1250, -1046, -1250, '文字', '東亞',
    '晚商王室以刻辭甲骨記錄占卜，是中國早期成熟文字的重要實物證據。年代為約數。',
    'The British Museum, Chinese oracle bone collection.',
    'https://www.britishmuseum.org/collection/object/A_1899-1209-1', 95, true),
  ('confucius', '孔子', 'Confucius', -551, -479, -551, '人物', '東亞',
    '孔丘，春秋時期思想家與教育家；傳統生卒年為BC551至BC479。',
    'Stanford Encyclopedia of Philosophy, Confucius.',
    'https://plato.stanford.edu/entries/confucius/', 100, true),
  ('socrates', '蘇格拉底', 'Socrates', -470, -399, -470, '人物', '希臘',
    '古典雅典哲學家，通常記為約BC470至BC399；其思想主要由後世作者記錄。',
    'Stanford Encyclopedia of Philosophy, Socrates.',
    'https://plato.stanford.edu/entries/socrates/', 90, true),
  ('alexander-great', '亞歷山大大帝', 'Alexander the Great',
    -356, -323, -356, '人物', '馬其頓與希臘世界',
    '馬其頓國王亞歷山大三世建立橫跨東地中海、埃及與西亞的帝國。',
    'The British Museum, Alexander the Great collection resources.',
    'https://www.britishmuseum.org/collection/term/BIOG52140', 85, true),
  ('qin-unification', '秦始皇統一六國', 'Qin unification of China',
    -221, -221, -221, '政治', '東亞',
    '秦王政完成兼併六國並建立皇帝制度，成為中國歷史的重要時間錨點。',
    'UNESCO World Heritage Centre, Mausoleum of the First Qin Emperor.',
    'https://whc.unesco.org/en/list/441/', 100, true)
on conflict ("Slug") do update set
  "TitleZh" = excluded."TitleZh",
  "TitleEn" = excluded."TitleEn",
  "StartYear" = excluded."StartYear",
  "EndYear" = excluded."EndYear",
  "TriggerYear" = excluded."TriggerYear",
  "Category" = excluded."Category",
  "RegionName" = excluded."RegionName",
  "SummaryZh" = excluded."SummaryZh",
  "SourceCitation" = excluded."SourceCitation",
  "SourceURL" = excluded."SourceURL",
  "DisplayPriority" = excluded."DisplayPriority",
  "IsPublished" = excluded."IsPublished",
  "UpdatedAt" = now();

create or replace function public."P118_GetContextEvents"()
returns table (
  "EventID" bigint,
  "Slug" text,
  "TitleZh" text,
  "TitleEn" text,
  "StartYear" integer,
  "EndYear" integer,
  "TriggerYear" integer,
  "Category" text,
  "RegionName" text,
  "SummaryZh" text,
  "SourceCitation" text,
  "SourceURL" text,
  "DisplayPriority" integer
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    e."EventID", e."Slug", e."TitleZh", e."TitleEn",
    e."StartYear", e."EndYear", e."TriggerYear",
    e."Category", e."RegionName", e."SummaryZh",
    e."SourceCitation", e."SourceURL", e."DisplayPriority"
  from public."TblP118ContextEvent" e
  where e."IsPublished" = true
  order by e."TriggerYear", e."DisplayPriority" desc, e."EventID";
$$;

grant select on public."TblP118ContextEvent" to anon, authenticated;
grant execute on function public."P118_GetContextEvents"() to anon, authenticated;

commit;

-- 執行後應回傳10筆公開事件。
select
  "TitleZh" as "全球事件",
  "TriggerYear" as "觸發年代",
  "Category" as "類別",
  "RegionName" as "地區"
from public."TblP118ContextEvent"
where "IsPublished" = true
order by "TriggerYear", "DisplayPriority" desc;
